/** Property allowlist shared by Astro pages and the generated Registry shell. */
export const ANALYTICS_EVENT_PROPS = Object.freeze({
  chart_submitted: ['mode'],
  chart_computed: ['mode', 'source'],
  chart_saved: ['source'],
  second_chart_saved: [],
  compat_submitted: ['source'],
  compat_computed: ['source'],
  horoscope_chart_click: ['surface'],
  email_subscribed: ['placement'],
  share_card_downloaded: ['variant'],
  widget_embed_copied: ['widget', 'mode'],
  registry_visit: [],
  verifier_used: ['chain', 'outcome'],
  sdk_click: ['source', 'destination'],
  wallet_chart_computed: ['chain', 'holds_registry_asset'],
  aura_view: [],
  aura_compose: ['outcome', 'held_bucket'],
  aura_share: ['outcome'],
  aura_refresh: ['outcome'],
  aura_calculator: ['direction'],
  aura_entry: ['source'],
  aura_return: ['interval'],
  aura_response: ['value'],
  aura_cabinet_select: [],
  aura_cabinet_reveal: ['outcome'],
  aura_talisman_personalize: ['state'],
  invite_created: ['notify'],
  invite_opened: ['state'],
  invite_completed: [],
  invite_returned: ['method'],
  invite_converted: ['action'],
  invite_revoked: [],

  // Existing event names remain accepted so historical funnels do not break.
  result_rendered: ['mode'],
  explorer_interaction: ['mode', 'source'],
  tour_start: ['variant'],
  tour_complete: ['variant'],
  tour_step: ['step'],
  context_help_opened: ['term', 'surface'],
  first_reading_prompt: ['action'],
  first_reading_step: ['step'],
  first_reading_completed: [],
  next_action_clicked: ['state', 'action'],
  email_capture_viewed: ['placement'],
  search_open: [],
  search_go: ['kind'],
  assistant_open: [],
  assistant_reply: [],
  push_prompt: [],
  push_subscribe: [],
  today_view: [],
  calendar_subscribe: [],
  chart_save: ['source'],
  chart_share: ['variant'],
  wing_entry: ['source'],
  lens_change: ['lens'],
  transit_search: ['span', 'bodies'],
  srchart_view: ['via'],
  composite_view: [],
  grid_select: [],
  chiron_toggle: ['on'],
  detail_toggle: ['to'],
  chart_name_set: ['via'],
  comm_read_view: [],
});

/** Closed-value contracts for the sharing loop's non-identifying dimensions. */
export const ANALYTICS_EVENT_VALUES = Object.freeze({
  chart_submitted: Object.freeze({
    mode: Object.freeze(['full', 'moon', 'rising']),
  }),
  chart_computed: Object.freeze({
    mode: Object.freeze(['full', 'moon', 'rising']),
    source: Object.freeze(['form', 'shared']),
  }),
  chart_saved: Object.freeze({
    source: Object.freeze(['free', 'tour', 'pair', 'invite_pair', 'invite']),
  }),
  compat_submitted: Object.freeze({
    source: Object.freeze(['form', 'restored', 'invite']),
  }),
  compat_computed: Object.freeze({
    source: Object.freeze(['form', 'restored', 'invite', 'returned']),
  }),
  horoscope_chart_click: Object.freeze({
    surface: Object.freeze(['hub', 'sign']),
  }),
  invite_opened: Object.freeze({
    state: Object.freeze(['ready', 'invalid', 'closed', 'used', 'unavailable', 'offline']),
  }),
  invite_returned: Object.freeze({
    method: Object.freeze(['share', 'copy', 'download']),
  }),
  invite_converted: Object.freeze({
    action: Object.freeze(['saved_chart', 'saved_pair', 'own_chart']),
  }),
});
