export const SR_COPY = {
  noon: 'Computed from a noon chart — the return instant can shift a few hours with your exact birth time, and houses need it.',
  noPlace: 'This saved chart has no stored birthplace, so the return is shown planets-only.',
  asc: {
    aries: "The year leads with ignition — you'll be handed situations that reward starting before you feel ready. Momentum is this year's currency.",
    taurus: 'The year leads with consolidation — building, furnishing, and letting good things get boring in the best way. Slow is the strategy, not the setback.',
    gemini: "The year leads with traffic — conversations, short trips, twice the usual inbox. Your calendar becomes the chart's main character.",
    cancer: 'The year leads with home in the load-bearing sense: where you live, who counts as family, what safety costs. Tend the base and the rest follows.',
    leo: 'The year leads with visibility — you get seen more, on purpose and not. Decide early what you want the audience to find.',
    virgo: "The year leads with maintenance — health, systems, the backlog you've been stepping over. Unglamorous fixes pay this year's best dividends.",
    libra: 'The year leads with other people — partnerships tighten, negotiations multiply, and "we" outvotes "I" more than usual. Choose counterparts carefully.',
    scorpio: 'The year leads with depth — shared resources, real intimacy, and at least one honest reckoning. What survives this year was built to.',
    sagittarius: 'The year leads with range — travel, study, or a belief that needs field-testing. The far option is usually the right one this year.',
    capricorn: "The year leads with the ledger — career, reputation, and the long game asking for its installment. Effort placed now compounds unusually well.",
    aquarius: "The year leads with the network — allies, groups, and the future you're actually building versus the one you inherited. Find your people; the plan follows.",
    pisces: 'The year leads with the tide — rest, imagination, and endings that make room. Not every year is for output; this one profits from margin.',
  },
  sunHouse: {
    1: "The Sun returns in the return-chart's first house: a self-definition year. How you show up gets renovated, visibly.",
    2: "A resources year — money, skills, and what you're actually worth on the open market. Value gets counted, then corrected upward or down.",
    3: 'A local year — words, siblings, neighborhoods, the daily loop. Small communications carry outsized freight.',
    4: 'A foundations year — housing, family, the private floor under the public life. Expect the center of gravity to move homeward.',
    5: 'An expression year — romance, play, children, work signed with your own name. What you make for joy matters more than usual.',
    6: "A working year — routines, health, the craft of the everyday. The body keeps this year's minutes; read them.",
    7: 'A partnership year — one relationship, personal or professional, becomes the plot. Contracts in every sense.',
    8: 'A depths year — shared money, inheritance in the broad sense, intimacy with stakes. Some doors close so others can pressurize.',
    9: "A horizon year — study, travel, publishing, belief under revision. Distance clarifies what proximity couldn't.",
    10: 'A summit year — career, standing, the public ledger. Work done in previous years gets graded now.',
    11: 'An alliance year — groups, friendships, the long-term project that needs more hands than yours. The future arrives by committee.',
    12: 'A closing year — rest, retreat, the compost cycle before the next twelve. Endings here are preparation wearing a disguise.',
  } as Record<number, string>,
} as const;
