export const WALLET_CHART_EN = {
  metaTitle: 'Wallet Natal Chart — Read-only Registry Instrument | Zodiacs.org',
  metaDescription: 'Paste a Solana or Base address to map its earliest supported on-chain timestamp as a symbolic, planets-only chart. No connection, signing, or transaction.',
  applicationCategory: 'EntertainmentApplication',
  breadcrumbRegistry: 'Registry',
  breadcrumbPage: 'Wallet natal chart',
  kicker: 'Registry instrument · read-only',
  title: 'A symbolic chart for a public address.',
  intro: 'A wallet has an earliest recorded transaction time, but no birthplace. This instrument maps that public UTC timestamp to planets in signs only.',
  boundary: 'Paste an address. There is no wallet connection, message signing, approval, transaction construction, or custody.',
  addressLabel: 'Solana or Base address',
  addressPlaceholder: 'Paste a public address',
  addressHelp: 'Accepted formats: a 32-byte Solana base58 public key or a Base 0x address.',
  supportedNetworks: 'Configured networks: {networks}.',
  solana: 'Solana',
  base: 'Base',
  calculate: 'Find the wallet’s chart',
  calculating: 'Reading public history…',
  notFound: 'Not found in the official Zodiacs.org registry.',
  unavailable: 'Public chain history is temporarily unavailable. No identity or verification status has changed.',
  historyTooDeep: 'This address exceeds the configured Solana history boundary. An archival provider with a higher page budget is required; no partial timestamp is shown.',
  invalidResponse: 'The history provider returned an unreadable result. Try again later.',
  noJavaScript: 'JavaScript is required for the private, in-browser astronomical calculation. The address lookup and chart computation do not run without your action.',
  resultKicker: 'Public timestamp receipt',
  resultTitle: '{address} maps to {time}.',
  resultChain: 'Network',
  resultSource: 'Timestamp source',
  sourceSolana: 'Paginated Solana signature history',
  sourceBaseExplorer: 'Base explorer account history',
  sourceBaseRpc: 'Base archive RPC · earliest outgoing activity',
  sourceBaseRpcCaveat: 'Standard Base RPC cannot index earlier incoming transfers. This fallback identifies the earliest outgoing transaction only.',
  utcOnly: 'UTC time · no birthplace · no houses or angles',
  placementsTitle: 'Planets in signs',
  placementsIntro: 'These placements use the returned UTC instant. A rising sign and houses would require a birthplace, which a wallet does not have.',
  retrograde: 'retrograde',
  officialHoldingsTitle: 'Official Registry context',
  officialHoldingsIntro: 'A read-only balance check found official Registry assets for these signs:',
  elementBalance: 'Held-sign element balance: {balance}.',
  ownerStart: 'Compare with your chart',
  ownerTitle: 'You × your wallet',
  ownerIntro: 'Optionally calculate planets-only synastry against your birth moment. Place is used only to resolve historical local time.',
  ownerPrivacy: 'Your birth date, time, place, planetary positions, and synastry stay in this browser. They are never sent to the wallet-history endpoint.',
  ownerTimeHelp: 'If the time is unknown, the engine uses local noon and omits any claim about fast-moving angles.',
  ownerPlaceHelp: 'Place selects the historical time zone from the site’s local city data; no coordinates enter the chart.',
  ownerSubmit: 'Calculate private synastry',
  ownerCalculating: 'Calculating in this browser…',
  ownerCancel: 'Clear private comparison',
  ownerMissing: 'Enter a birth date and choose a birthplace before calculating.',
  synastryTitle: 'Symbolic synastry',
  synastryFlow: 'The tight contacts lean more flowing than frictional.',
  synastryCharge: 'The tight contacts lean more frictional than flowing.',
  synastryBalance: 'Flow and friction are evenly represented in the tight contacts.',
  synastryContact: 'Your {ownerBody} is in {aspect} to the wallet’s {walletBody} ({orb}° orb).',
  synastryNoContact: 'No major aspect falls within the engine’s standard orbs.',
  share: 'Share this symbolic chart',
  sharing: 'Preparing the private card…',
  shareComplete: 'Share card ready.',
  shareError: 'The share card could not be created on this device.',
  cardTitle: 'Wallet natal chart',
  cardBorn: 'Public chart time · {time}',
  cardNoBirthplace: 'UTC · planets only · no birthplace',
  cardOwnerHighlight: 'Owner synastry · {ownerBody} {aspect} wallet {walletBody} · {orb}°',
  cardSymbolic: 'Symbolic context · read-only · not financial advice',
  privacyTitle: 'What crosses the boundary',
  privacyBody: 'The server receives the pasted public address and returns a public timestamp. Optional owner birth details and all astronomical computation stay on this device.',
  readOnlyDisclosure: 'Read-only by design. No custody, signing, approvals, or transactions.',
  entertainmentDisclosure: 'For entertainment and symbolic context only.',
  financialDisclosure: 'Not financial advice. Nothing here is a solicitation, recommendation, or statement of value.',
  registryBack: 'Return to the official Registry',
} as const;

export type WalletChartStringKey = keyof typeof WALLET_CHART_EN;

export function walletText(
  key: WalletChartStringKey,
  values: Record<string, string | number> = {},
): string {
  return WALLET_CHART_EN[key].replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? ''));
}
