/**
 * Tour copy — module-local dictionary, both locales, compile-time key
 * parity via `satisfies` (the SHARE_COPY precedent in
 * PositionsShareSurface.tsx). Lives inside the lazy tour module so none of
 * these strings land in any page's initial JS closure — /birth-chart/ has
 * fractions of a kilobyte of budget headroom and the shared UI dictionary
 * is statically imported by every page.
 *
 * Voice: plain, warm, specific. State computed facts; label interpretation
 * as tradition; never woo, never salesy.
 */
import type { Locale } from '../../../lib/i18n';

const TOUR_COPY = {
  en: {
    // Chrome
    kicker: 'Chapter {n} of {total}',
    next: 'Next',
    prev: 'Back',
    finish: 'Finish the tour',
    exitAria: 'End the tour',
    dotsLabel: 'Chapters',
    dotAria: '{title} — chapter {n} of {total}',
    ended: 'Tour ended.',
    backToTour: '← Back to the tour',
    allTypes: 'All',
    aspectTypesLabel: 'Aspect types',
    previewNote: 'A preview only — your chart stays in {system}. Change it in the form above.',
    rotateToAries: 'Put 0° Aries on the left',
    rotateToAsc: 'Back to your Ascendant',
    morphToPlacidus: 'See it in Placidus',
    morphToWhole: 'See it in whole sign',
    diffCount: '{n} placements change house',
    diffOne: '1 placement changes house',
    diffNone: 'No placements change house for this birth',
    polarNote: "This far from the equator Placidus isn't defined, so this chart uses whole sign either way.",
    loudest: "This chart's four loudest:",
    wholeSign: 'whole sign',
    placidus: 'Placidus',

    // Chapters
    skyTitle: 'This is your sky',
    skyBody1: 'Everything on this wheel was computed from one instant: the sky over your birthplace at your birth time. Nothing is looked up — it is calculated, on your device.',
    skyBody2: 'The tour walks the wheel one layer at a time. Tap anything along the way; the tour waits.',
    zodiacTitle: 'The zodiac ring',
    zodiacBody1: "The outer ring is the zodiac: twelve equal 30° segments of the Sun's yearly path. It is the wheel's fixed scale — every position is read against it.",
    zodiacBody2: 'Your Sun stays lit — a sun sign just names the segment that one degree falls in.',
    zodiacRotateNote: 'Charts are usually drawn with your Ascendant on the left. The ring never changes — only where we start reading.',
    horizonTitle: 'Your horizon',
    horizonBody1: 'ASC marks the degree rising in the east at your birth minute; the sign it sits in is your rising sign. Straight across sits the Descendant, where the sky was setting; MC is the degree at its highest.',
    horizonBody2: 'This axis is why the minute matters: it moves about a degree every four minutes, and the whole wheel is anchored to it.',
    'big-threeTitle': 'The big three',
    'big-threeBody1': 'Sun, Moon, rising — identity, instinct, entrance. Read these three first; everything else refines them.',
    planetsTitle: 'The planets',
    planetsBody1: 'Each disc is a planet at its true degree. Mercury through Mars move fast and read personally; Jupiter and Saturn move in years and set the longer themes; the outer three mark generations.',
    planetsBody2: 'Tap any disc for its receipt — position, speed, house, aspects. Rx means retrograde: apparent backward motion, common and ordinary.',
    housesTitle: 'The houses',
    housesBody1: 'The twelve wedges are the houses — where in life a planet does its work. They come from your birth time and place, not the calendar.',
    housesBody2: 'Two honest ways to slice them: whole sign gives each house one sign; Placidus divides by exact horizon math. Try the other one — the planets never move, only the walls.',
    aspectsTitle: 'The conversations',
    aspectsBody1: 'The chords in the middle are aspects: set angles between planets, each a kind of conversation. Thicker chords sit closer to exact — they do the most work; dashed ones are already separating.',
    wholeTitle: 'The whole picture',
    wholeBody1: "Everything back on. A chart isn't a list of traits — it's one sky with everything happening at once. The reading below walks it line by line.",
    wholeBody2: 'Save it and your profile page computes its year ahead — still on this device. The share link carries the data in the link itself; it never touches a server.',
    'no-housesTitle': 'Why this chart has no houses',
    'no-housesBody1': "Houses come from the exact minute of birth — the sky's rotation, not the calendar. Without a time we compute a noon chart: every planet's sign is right — except sometimes the Moon, which can change sign within a day — and there is no horizon to hang houses on.",
    'no-housesBody2': 'If the time ever turns up (birth certificates usually have it), add it above — the wheel gains its rooms, and you gain a rising sign.',
  },
  es: {
    kicker: 'Capítulo {n} de {total}',
    next: 'Siguiente',
    prev: 'Atrás',
    finish: 'Terminar el recorrido',
    exitAria: 'Salir del recorrido',
    dotsLabel: 'Capítulos',
    dotAria: '{title} — capítulo {n} de {total}',
    ended: 'Recorrido terminado.',
    backToTour: '← Volver al recorrido',
    allTypes: 'Todos',
    aspectTypesLabel: 'Tipos de aspecto',
    previewNote: 'Solo una vista previa — tu carta sigue en {system}. Cambia el sistema en el formulario de arriba.',
    rotateToAries: 'Poner 0° de Aries a la izquierda',
    rotateToAsc: 'Volver a tu ascendente',
    morphToPlacidus: 'Verla en Placidus',
    morphToWhole: 'Verla en signos completos',
    diffCount: '{n} posiciones cambian de casa',
    diffOne: '1 posición cambia de casa',
    diffNone: 'Ninguna posición cambia de casa para este nacimiento',
    polarNote: 'Tan lejos del ecuador, Placidus no está definido, así que esta carta usa signos completos de todos modos.',
    loudest: 'Los cuatro más fuertes de esta carta:',
    wholeSign: 'signos completos',
    placidus: 'Placidus',

    skyTitle: 'Este es tu cielo',
    skyBody1: 'Todo en esta rueda se calculó a partir de un instante: el cielo sobre tu lugar de nacimiento a tu hora de nacimiento. Nada se busca en tablas — se calcula, en tu dispositivo.',
    skyBody2: 'El recorrido repasa la rueda capa por capa. Toca lo que quieras por el camino; el recorrido espera.',
    zodiacTitle: 'El anillo del zodiaco',
    zodiacBody1: 'El anillo exterior es el zodiaco: doce segmentos iguales de 30° del camino anual del Sol. Es la regla fija de la rueda: cada posición se mide sobre ella.',
    zodiacBody2: 'Tu Sol sigue encendido — un signo solar solo nombra el segmento donde cae ese grado.',
    zodiacRotateNote: 'Las cartas suelen dibujarse con tu ascendente a la izquierda. El anillo no cambia — solo dónde empezamos a leer.',
    horizonTitle: 'Tu horizonte',
    horizonBody1: 'ASC marca el grado que subía por el este en tu minuto de nacimiento — tu ascendente. Justo enfrente está el descendente, donde el cielo se ponía; el MC es el grado en lo más alto.',
    horizonBody2: 'Este eje es la razón de que importe el minuto: se mueve alrededor de un grado cada cuatro minutos, y toda la rueda está anclada a él.',
    'big-threeTitle': 'Los tres grandes',
    'big-threeBody1': 'Sol, Luna, ascendente: identidad, instinto, presencia. Lee estos tres primero; todo lo demás los matiza.',
    planetsTitle: 'Los planetas',
    planetsBody1: 'Cada disco es un planeta en su grado real. De Mercurio a Marte van rápido y se leen en clave personal; Júpiter y Saturno marcan los temas de largo plazo; los tres exteriores marcan generaciones.',
    planetsBody2: 'Toca cualquier disco para ver su ficha — posición, velocidad, casa, aspectos. Rx significa retrógrado: movimiento aparente hacia atrás, común y corriente.',
    housesTitle: 'Las casas',
    housesBody1: 'Las doce cuñas son las casas — en qué parte de la vida trabaja cada planeta. Salen de tu hora y lugar de nacimiento, no del calendario.',
    housesBody2: 'Dos maneras honestas de dividirlas: el sistema de signos completos da un signo a cada casa; Placidus divide con la trigonometría exacta del horizonte. Prueba la otra — los planetas no se mueven, solo las paredes.',
    aspectsTitle: 'Las conversaciones',
    aspectsBody1: 'Las cuerdas del centro son aspectos: ángulos fijos entre planetas, cada uno un tipo de conversación. Las cuerdas más gruesas son ángulos más exactos — son las de mayor peso; las discontinuas ya se están separando.',
    wholeTitle: 'La imagen completa',
    wholeBody1: 'Todo encendido otra vez. Una carta no es una lista de rasgos — es un solo cielo con todo a la vez. La lectura de abajo la recorre línea por línea.',
    wholeBody2: 'Guárdala y tu página de perfil calcula sus próximos doce meses — siempre en este dispositivo. El enlace para compartir lleva los datos dentro del propio enlace; nunca pasa por un servidor.',
    'no-housesTitle': 'Por qué esta carta no tiene casas',
    'no-housesBody1': 'Las casas salen del minuto exacto del nacimiento — la rotación del cielo, no el calendario. Sin hora calculamos una carta de mediodía: el signo de cada planeta es correcto — salvo a veces el de la Luna, que puede cambiar de signo dentro del día — pero no hay horizonte del que colgar las casas.',
    'no-housesBody2': 'Si la hora aparece algún día (el certificado de nacimiento suele tenerla), agrégala arriba — la rueda gana sus casas, y tú un ascendente.',
  },
  pt: {
    kicker: 'Capítulo {n} de {total}',
    next: 'Próximo',
    prev: 'Voltar',
    finish: 'Concluir o passeio',
    exitAria: 'Encerrar o passeio',
    dotsLabel: 'Capítulos',
    dotAria: '{title} — capítulo {n} de {total}',
    ended: 'Passeio encerrado.',
    backToTour: '← Voltar ao passeio',
    allTypes: 'Todos',
    aspectTypesLabel: 'Tipos de aspecto',
    previewNote: 'Apenas uma prévia — seu mapa continua em {system}. Mude o sistema no formulário acima.',
    rotateToAries: 'Colocar 0° de Áries à esquerda',
    rotateToAsc: 'Voltar ao seu ascendente',
    morphToPlacidus: 'Ver em Placidus',
    morphToWhole: 'Ver em signos inteiros',
    diffCount: '{n} posições mudam de casa',
    diffOne: '1 posição muda de casa',
    diffNone: 'Nenhuma posição muda de casa neste nascimento',
    polarNote: 'Tão longe do equador, Placidus não é definido; por isso, este mapa usa signos inteiros de qualquer forma.',
    loudest: 'Os quatro aspectos mais fortes deste mapa:',
    wholeSign: 'signos inteiros',
    placidus: 'Placidus',

    skyTitle: 'Este é o seu céu',
    skyBody1: 'Tudo nesta roda foi calculado a partir de um instante: o céu sobre seu local de nascimento na hora em que você nasceu. Nada é consultado em tabelas — tudo é calculado no seu dispositivo.',
    skyBody2: 'O passeio percorre a roda, uma camada de cada vez. Toque no que quiser durante o caminho; o passeio espera.',
    zodiacTitle: 'O anel do zodíaco',
    zodiacBody1: 'O anel externo é o zodíaco: doze segmentos iguais de 30° no caminho anual do Sol. É a escala fixa da roda — cada posição é lida em relação a ela.',
    zodiacBody2: 'Seu Sol continua aceso — o signo solar apenas dá nome ao segmento em que esse grau cai.',
    zodiacRotateNote: 'Os mapas costumam ser desenhados com o ascendente à esquerda. O anel nunca muda — muda apenas o ponto em que começamos a leitura.',
    horizonTitle: 'Seu horizonte',
    horizonBody1: 'ASC marca o grau que surgia a leste no minuto do seu nascimento; o signo em que ele está é seu ascendente. Exatamente do outro lado está o descendente, onde o céu se punha; MC é o grau no ponto mais alto.',
    horizonBody2: 'Este eixo mostra por que o minuto importa: ele se move cerca de um grau a cada quatro minutos, e toda a roda se ancora nele.',
    'big-threeTitle': 'Os três grandes',
    'big-threeBody1': 'Sol, Lua, ascendente — identidade, instinto, presença. Leia estes três primeiro; todo o resto acrescenta nuances.',
    planetsTitle: 'Os planetas',
    planetsBody1: 'Cada disco é um planeta em seu grau real. De Mercúrio a Marte, eles se movem rápido e têm uma leitura pessoal; Júpiter e Saturno se movem ao longo de anos e definem temas mais longos; os três externos marcam gerações.',
    planetsBody2: 'Toque em qualquer disco para ver os detalhes — posição, velocidade, casa e aspectos. Rx significa retrógrado: movimento aparente para trás, comum e normal.',
    housesTitle: 'As casas',
    housesBody1: 'As doze fatias são as casas — onde cada planeta atua na vida. Elas vêm da hora e do local de nascimento, não do calendário.',
    housesBody2: 'Duas formas honestas de dividi-las: signos inteiros atribuem um signo a cada casa; Placidus divide pela matemática exata do horizonte. Experimente a outra — os planetas nunca se movem, apenas as paredes.',
    aspectsTitle: 'As conversas',
    aspectsBody1: 'As cordas no centro são aspectos: ângulos definidos entre planetas, cada um como um tipo de conversa. Cordas mais grossas ficam mais perto do ponto exato — elas têm mais peso; as tracejadas já estão se separando.',
    wholeTitle: 'O quadro completo',
    wholeBody1: 'Tudo aceso novamente. Um mapa não é uma lista de traços — é um único céu com tudo acontecendo ao mesmo tempo. A leitura abaixo o percorre linha por linha.',
    wholeBody2: 'Salve-o e sua página de perfil calcula os próximos doze meses — sempre neste dispositivo. O link de compartilhamento leva os dados no próprio link; eles nunca passam por um servidor.',
    'no-housesTitle': 'Por que este mapa não tem casas',
    'no-housesBody1': 'As casas vêm do minuto exato do nascimento — da rotação do céu, não do calendário. Sem um horário, calculamos um mapa do meio-dia: o signo de cada planeta está correto — com a possível exceção da Lua, que pode mudar de signo no mesmo dia — e não existe horizonte para sustentar as casas.',
    'no-housesBody2': 'Se o horário aparecer algum dia (a certidão de nascimento costuma registrá-lo), adicione-o acima — a roda ganha suas casas, e você ganha um ascendente.',
  },
  fr: {
    kicker: 'Chapitre {n} sur {total}',
    next: 'Suivant',
    prev: 'Retour',
    finish: 'Terminer la visite',
    exitAria: 'Quitter la visite',
    dotsLabel: 'Chapitres',
    dotAria: '{title} — chapitre {n} sur {total}',
    ended: 'Visite terminée.',
    backToTour: '← Revenir à la visite',
    allTypes: 'Tous',
    aspectTypesLabel: 'Types d’aspects',
    previewNote: 'Aperçu uniquement — ton thème reste en {system}. Change ce réglage dans le formulaire ci-dessus.',
    rotateToAries: 'Placer 0° du Bélier à gauche',
    rotateToAsc: 'Revenir à ton ascendant',
    morphToPlacidus: 'Voir en Placidus',
    morphToWhole: 'Voir en signes entiers',
    diffCount: '{n} positions changent de maison',
    diffOne: '1 position change de maison',
    diffNone: 'Aucune position ne change de maison pour cette naissance',
    polarNote: 'À cette distance de l’équateur, Placidus n’est pas défini ; ce thème utilise donc les signes entiers dans tous les cas.',
    loudest: 'Les quatre aspects les plus marqués de ce thème :',
    wholeSign: 'signes entiers',
    placidus: 'Placidus',

    skyTitle: 'Voici ton ciel',
    skyBody1: 'Tout ce qui figure sur cette roue a été calculé à partir d’un seul instant : le ciel au-dessus de ton lieu de naissance à l’heure de ta naissance. Rien n’est extrait d’une table — tout est calculé sur ton appareil.',
    skyBody2: 'La visite parcourt la roue couche par couche. Touche ce que tu veux en chemin ; la visite attendra.',
    zodiacTitle: 'L’anneau du zodiaque',
    zodiacBody1: 'L’anneau extérieur est le zodiaque : douze segments égaux de 30° sur le parcours annuel du Soleil. C’est l’échelle fixe de la roue — chaque position se lit par rapport à elle.',
    zodiacBody2: 'Ton Soleil reste mis en évidence — un signe solaire désigne simplement le segment dans lequel tombe ce degré.',
    zodiacRotateNote: 'Les thèmes sont généralement dessinés avec l’ascendant à gauche. L’anneau ne change jamais — seul le point de départ de la lecture se déplace.',
    horizonTitle: 'Ton horizon',
    horizonBody1: 'L’ASC marque le degré qui se levait à l’est à la minute de ta naissance ; le signe où il se trouve est ton ascendant. Juste en face se trouve le descendant, là où le ciel se couchait ; le MC correspond au degré qui était au plus haut.',
    horizonBody2: 'Cet axe explique pourquoi la minute compte : il se déplace d’environ un degré toutes les quatre minutes, et toute la roue s’y ancre.',
    'big-threeTitle': 'Les trois piliers',
    'big-threeBody1': 'Soleil, Lune, ascendant — identité, instinct, présence. Lis ces trois éléments en premier ; tout le reste les précise.',
    planetsTitle: 'Les planètes',
    planetsBody1: 'Chaque disque représente une planète à son degré réel. De Mercure à Mars, les planètes se déplacent vite et se lisent sur un plan personnel ; Jupiter et Saturne avancent sur plusieurs années et donnent les thèmes de fond ; les trois planètes extérieures marquent les générations.',
    planetsBody2: 'Touche un disque pour voir ses données — position, vitesse, maison, aspects. Rx signifie rétrograde : un mouvement apparent vers l’arrière, courant et ordinaire.',
    housesTitle: 'Les maisons',
    housesBody1: 'Les douze secteurs sont les maisons — les domaines de la vie où chaque planète agit. Ils viennent de ton heure et de ton lieu de naissance, pas du calendrier.',
    housesBody2: 'Deux façons rigoureuses de les diviser : les signes entiers attribuent un signe à chaque maison ; Placidus s’appuie sur le calcul exact de l’horizon. Essaie l’autre méthode — les planètes ne bougent jamais, seules les limites changent.',
    aspectsTitle: 'Les conversations',
    aspectsBody1: 'Les lignes au centre sont les aspects : des angles définis entre les planètes, chacun comme une forme de conversation. Les lignes plus épaisses sont plus proches de l’exactitude — elles pèsent davantage ; celles en pointillé sont déjà en train de se séparer.',
    wholeTitle: 'La vue d’ensemble',
    wholeBody1: 'Tout est de nouveau visible. Un thème n’est pas une liste de traits — c’est un seul ciel où tout se produit en même temps. La lecture ci-dessous le parcourt ligne par ligne.',
    wholeBody2: 'Enregistre-le et ta page de profil calcule son année à venir — toujours sur cet appareil. Le lien de partage contient les données dans le lien lui-même ; elles ne passent jamais par un serveur.',
    'no-housesTitle': 'Pourquoi ce thème n’a pas de maisons',
    'no-housesBody1': 'Les maisons viennent de la minute exacte de naissance — de la rotation du ciel, pas du calendrier. Sans heure, nous calculons un thème pour midi : le signe de chaque planète est correct — sauf parfois celui de la Lune, qui peut changer de signe au cours de la journée — mais il n’y a aucun horizon auquel rattacher les maisons.',
    'no-housesBody2': 'Si l’heure refait surface un jour — elle figure souvent sur l’acte de naissance — ajoute-la ci-dessus : la roue gagne ses maisons et toi, un ascendant.',
  },
} as const satisfies Record<Locale, Record<string, string>>;

export type TourKey = keyof typeof TOUR_COPY.en;

export function tourText(locale: Locale, key: TourKey): string {
  return TOUR_COPY[locale][key];
}

export function tourFormat(
  locale: Locale,
  key: TourKey,
  values: Record<string, string | number>,
): string {
  return tourText(locale, key).replace(/\{([a-zA-Z][a-zA-Z0-9]*)\}/g, (token, name: string) => (
    Object.prototype.hasOwnProperty.call(values, name) ? String(values[name]) : token
  ));
}
