#!/usr/bin/env bash
set -Eeuo pipefail

export LC_ALL=C
umask 077

restore_script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
restore_work_dir="$(mktemp -d)"
restore_passphrase_file="${restore_work_dir}/.backup-passphrase"
restore_url_file="${restore_work_dir}/.target-url"
restore_pgpass_file="${restore_work_dir}/.pgpass"
restore_env_file="${restore_work_dir}/.pg-env"
restore_archive="${restore_work_dir}/backup.tar.gz"
restore_bundle_dir="${restore_work_dir}/bundle"
production_project_ref="mftpcdpttteuwbolobye"

cleanup_restore() {
  if [[ -n "${restore_work_dir}" && "${restore_work_dir}" != "/" && -d "${restore_work_dir}" ]]; then
    rm -rf -- "${restore_work_dir}"
  fi
}

trap cleanup_restore EXIT
trap 'exit 130' INT
trap 'exit 143' TERM HUP

if [[ "$#" -ne 1 || ! -f "$1" ]]; then
  echo "Usage: bash scripts/restore-db-backup.sh /path/to/zodiacs-db-....tar.gz.gpg" >&2
  exit 2
fi
restore_artifact="$1"

for restore_command in node psql gpg tar; do
  if ! command -v "${restore_command}" >/dev/null 2>&1; then
    echo "${restore_command} is required." >&2
    exit 1
  fi
done
if [[ ! "$(psql --version)" =~ \(PostgreSQL\)[[:space:]]17\. ]]; then
  echo "PostgreSQL 17 client tools are required." >&2
  exit 1
fi

printf 'Backup passphrase (input hidden): ' >&2
IFS= read -r -s restore_passphrase
printf '\n' >&2
if [[ -z "${restore_passphrase}" ]]; then
  echo "A backup passphrase is required." >&2
  exit 1
fi
printf '%s\n' "${restore_passphrase}" > "${restore_passphrase_file}"
unset restore_passphrase
chmod 0600 "${restore_passphrase_file}"

exec 3<"${restore_passphrase_file}"
rm -f -- "${restore_passphrase_file}"
if ! gpg \
  --batch \
  --quiet \
  --pinentry-mode loopback \
  --no-symkey-cache \
  --decrypt \
  --passphrase-fd 3 \
  --output "${restore_archive}" \
  "${restore_artifact}"; then
  echo "Backup decryption failed." >&2
  exit 1
fi
exec 3<&-

expected_members=(
  BACKUP-METADATA.txt
  source-manifest.txt
  application-pre.sql
  auth-users.sql
  auth-identities.sql
  application-data.sql
  application-post.sql
)
mapfile -t archive_members < <(
  tar --list --gzip --file="${restore_archive}" --quoting-style=escape
)
if [[ "${#archive_members[@]}" -ne "${#expected_members[@]}" ]]; then
  echo "Backup archive has an unexpected member count." >&2
  exit 1
fi
for expected_member in "${expected_members[@]}"; do
  member_found=false
  for archive_member in "${archive_members[@]}"; do
    if [[ "${archive_member}" == "${expected_member}" ]]; then
      member_found=true
      break
    fi
  done
  if [[ "${member_found}" != true ]]; then
    echo "Backup archive is missing an expected member." >&2
    exit 1
  fi
done

mkdir "${restore_bundle_dir}"
tar \
  --extract \
  --gzip \
  --file="${restore_archive}" \
  --directory="${restore_bundle_dir}" \
  --no-same-owner \
  --no-same-permissions
for expected_member in "${expected_members[@]}"; do
  if [[ ! -f "${restore_bundle_dir}/${expected_member}" || -L "${restore_bundle_dir}/${expected_member}" ]]; then
    echo "Backup archive did not extract to regular files only." >&2
    exit 1
  fi
done
if ! grep -qx 'format=zodiacs-logical-backup-v2' \
  "${restore_bundle_dir}/BACKUP-METADATA.txt"; then
  echo "Unsupported backup bundle format." >&2
  exit 1
fi

printf 'Fresh target database URL (input hidden): ' >&2
IFS= read -r -s restore_target_url
printf '\n' >&2
if [[ -z "${restore_target_url}" ]]; then
  echo "A fresh target database URL is required." >&2
  exit 1
fi
printf '%s\n' "${restore_target_url}" > "${restore_url_file}"
unset restore_target_url
chmod 0600 "${restore_url_file}"

PG_CLIENT_URL_FILE="${restore_url_file}" \
PGPASSFILE="${restore_pgpass_file}" \
PG_CLIENT_ENV_FILE="${restore_env_file}" \
PG_CLIENT_APPNAME="zodiacs-restore-drill" \
  node "${restore_script_dir}/configure-pg-client.mjs"
rm -f -- "${restore_url_file}"
# shellcheck disable=SC1090 -- generated by the fixed repository helper.
source "${restore_env_file}"
rm -f -- "${restore_env_file}"

restore_host_lower="${PGHOST,,}"
restore_user_lower="${PGUSER,,}"
if [[ "${restore_host_lower}" == *"${production_project_ref}"* \
   || "${restore_user_lower}" == *"${production_project_ref}"* ]]; then
  echo "Restore refused: the target resolves to the current production project." >&2
  exit 1
fi

(
  cd -- "${restore_bundle_dir}"
  psql \
    -X \
    --no-password \
    --set ON_ERROR_STOP=1 \
    --set restore_preflight=1 \
    --file="${restore_script_dir}/db-restore-acceptance.sql"
)

echo "Fresh-project preflight passed. The next step resets public and creates the source migration ledger." >&2
printf 'Type RESTORE to run the atomic restore: ' >&2
IFS= read -r restore_confirmation
if [[ "${restore_confirmation}" != "RESTORE" ]]; then
  echo "Restore cancelled before any schema change." >&2
  exit 1
fi
unset restore_confirmation

(
  cd -- "${restore_bundle_dir}"
  psql \
    -X \
    --no-password \
    --set ON_ERROR_STOP=1 \
    --set VERBOSITY=terse \
    --set restore_preflight=0 \
    --single-transaction \
    --file="${restore_script_dir}/db-restore-prelude.sql" \
    --file="application-pre.sql" \
    --file="${restore_script_dir}/db-restore-auth-begin.sql" \
    --file="auth-users.sql" \
    --file="auth-identities.sql" \
    --file="${restore_script_dir}/db-restore-auth-end.sql" \
    --file="application-data.sql" \
    --file="application-post.sql" \
    --file="${restore_script_dir}/db-restore-acceptance.sql"
)

echo "Restore committed only after manifest, FK, constraint, RLS, ACL, and API-role acceptance passed."
echo "Sessions were intentionally excluded: every restored user must reauthenticate before the owner application smoke test."
