/**
 * Real data only. natal-chart.json and sky-now.json are generated by
 * video/tools/*.ts using the site's own engine (@zodiacs/engine v0.1.0);
 * this module just reshapes them for the scenes and applies the site's
 * wheel conventions (South Node hidden, drawn aspects capped at orb < 6,
 * weight tiers at 1.5°/3.5° — src/lib/scene/build.ts).
 */
import natalJson from '../data/natal-chart.json';
import skyJson from '../data/sky-now.json';
import { SIGN_ORDER, SIGN_NAMES } from './theme';

export interface WheelBodyDatum { body: string; lon: number; retrograde: boolean }
export interface WheelAspectDatum {
  a: string; b: string; type: string; orb: number; applying: boolean; weight: 0 | 1 | 2;
}

export const natal = natalJson;
export const sky = skyJson;

export const signIndexForLongitude = (lon: number): number =>
  Math.floor((((lon % 360) + 360) % 360) / 30);

export const signSlugForLongitude = (lon: number): string =>
  SIGN_ORDER[signIndexForLongitude(lon)];

export const degreeInSign = (lon: number): number => (((lon % 360) + 360) % 360) % 30;

/** 123.456 → "3°27′ Leo" — same formatting as site formatLongitude. */
export const formatLongitude = (lon: number): string => {
  const deg = degreeInSign(lon);
  const d = Math.floor(deg);
  const m = Math.floor((deg - d) * 60);
  return `${d}°${String(m).padStart(2, '0')}′ ${SIGN_NAMES[signSlugForLongitude(lon)]}`;
};

const aspectWeight = (orb: number): 0 | 1 | 2 => (orb <= 1.5 ? 2 : orb <= 3.5 ? 1 : 0);

/** Bodies as the site's wheel draws them (South Node hidden). */
export const wheelBodies: WheelBodyDatum[] = natal.bodies.filter((b) => b.body !== 'South Node');

/** Aspects as the site's wheel draws them (orb < 6). */
export const wheelAspects: WheelAspectDatum[] = natal.aspects
  .filter((a) => a.orb < 6)
  .map((a) => ({ ...a, weight: aspectWeight(a.orb) }));

const bodyLon = (name: string): number => natal.bodies.find((b) => b.body === name)!.lon;

export const bigThree = {
  sun: { sign: signSlugForLongitude(bodyLon('Sun')), label: formatLongitude(bodyLon('Sun')) },
  moon: { sign: signSlugForLongitude(bodyLon('Moon')), label: formatLongitude(bodyLon('Moon')) },
  rising: { sign: signSlugForLongitude(natal.angles.asc), label: formatLongitude(natal.angles.asc) },
};

/** "1993-06-16 · 16:30:00 UTC · 40.71°, -74.01° · Placidus houses · engine v0.1.0" — the site's receipt line. */
export const receipt = `${natal.input.date} · ${natal.utc.slice(11, 19)} UTC · ${natal.input.lat.toFixed(2)}°, ${natal.input.lon.toFixed(2)}° · Placidus houses · engine v${natal.engineVersion}`;

export const skyLines = (() => {
  const moon = sky.bodies.find((b) => b.body === 'Moon')!;
  const rx = sky.bodies.filter((b) => b.retrograde && !b.body.includes('Node'));
  const capturedUtc = `${sky.capturedAt.slice(0, 10)} · ${sky.capturedAt.slice(11, 16)} UTC`;
  const e = sky.nextEclipse;
  const eclipseDate = new Date(e.peak).toLocaleDateString('en-US', {
    month: 'short', day: 'numeric', timeZone: 'UTC',
  });
  return {
    capturedUtc,
    moonPhase: `${sky.moon.phase} · ${Math.round(sky.moon.illumination * 100)}% lit`,
    moonPos: `Moon ${formatLongitude(moon.lon)}`,
    retro: rx.length
      ? `${rx.map((b) => `${b.body} Rx`).join(' · ')} — all else direct`
      : 'All planets direct',
    eclipse: `${e.kind} ${e.type} eclipse · ${eclipseDate} · ${Math.round(e.degree)}° ${SIGN_NAMES[e.sign]}`,
  };
})();
