/**
 * Run the preregistered aberrated holdout, once, and write what it did.
 *
 *   node tools/measure/aberrated-holdout.mjs --pack /path/pack.zeph --out run.json
 *
 * The cases come from ABERRATED-PREREGISTRATION.md section 8a, which was
 * committed before this file existed. Nothing here chooses a case, a
 * tolerance or a pass rule; all four are transcribed.
 *
 * Every case runs all three rungs of section 4 on identical instants, so
 * the difference between rungs is a named correction rather than "error".
 */
import { writeFileSync } from 'node:fs';
import { openPackFile } from '../../src/node.mjs';
import { searchRetardedLongitude, searchAberratedLongitude } from '../../src/core/retarded-search.mjs';
import { searchGeometricLongitude } from '../../src/core/validated-search.mjs';
import { makeAberratedReference } from '../../test/tier-b/_aberrated-reference.mjs';

const args = new Map();
for (let i = 2; i < process.argv.length; i += 2) args.set(process.argv[i].replace(/^--/, ''), process.argv[i + 1]);
const PACK = args.get('pack');
const OUT = args.get('out') ?? null;
if (!PACK) throw new Error('--pack is required');

const DAY = 86400;
const J2000_UTC = Date.UTC(2000, 0, 1, 12);
/** The harness converts, never the operation. TDB = UTC - J2000 + 69.184 s. */
const tdb = (iso) => (Date.parse(iso) - J2000_UTC) / 1000 + 69.184;
const plus = (iso, days) => `${new Date(Date.parse(iso) + days * DAY * 1000).toISOString().slice(0, 10)}T00:00:00Z`;

const BODIES = ['Sun', 'Moon', 'Mercury', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'];
/** Well under the fastest crossing rate in each window; the light-time suite's constants. */
const STEP = { Moon: 300, Mercury: 900, Venus: 1800, Sun: 1800, Mars: 1800, Jupiter: 3600, Saturn: 3600, Uranus: 3600, Neptune: 3600, Pluto: 3600 };
/** Section 7. */
const ROOT_TOLERANCE_SEC = 1e-3;
const MATCH_WINDOW_SEC = 1;

const rt = await openPackFile(PACK);
const eph = rt.ephemeris;
const ref = makeAberratedReference(eph);

// ---- the cases, generated by the rule of section 8a and nothing else
const CASES = [];
BODIES.forEach((body, i) => {
  const from = plus('1975-01-01T00:00:00Z', 900 * i);
  const to = plus(from, 300);
  const mid = (tdb(from) + tdb(to)) / 2;
  const targetDeg = Number(ref.lonDeg(body, mid, true).toFixed(6));
  CASES.push({ id: `H${i + 1}`, series: 'main', body, from, to, targetDeg });
  CASES.push({ id: `A${i + 1}`, series: 'antipode', body, from, to, targetDeg: Number(((targetDeg + 180) % 360).toFixed(6)) });
});

const pair = (found, reference) => {
  // Greedy nearest matching inside the match window, both directions
  // counted, so a duplicate report is an extra and a lost root is a miss.
  const takenRef = new Set();
  const takenGot = new Set();
  const matched = [];
  for (let i = 0; i < found.length; i += 1) {
    let best = -1;
    let bestD = Infinity;
    for (let j = 0; j < reference.length; j += 1) {
      if (takenRef.has(j)) continue;
      const dd = Math.abs(found[i].tdbSec - reference[j]);
      if (dd < bestD) { bestD = dd; best = j; }
    }
    if (best >= 0 && bestD <= MATCH_WINDOW_SEC) {
      takenRef.add(best); takenGot.add(i);
      matched.push({ got: found[i], ref: reference[best], delta: found[i].tdbSec - reference[best] });
    }
  }
  return {
    matched,
    missed: reference.filter((_, j) => !takenRef.has(j)),
    extra: found.filter((_, i) => !takenGot.has(i)).map((e) => e.tdbSec),
  };
};

const rows = [];
for (const c of CASES) {
  const a = tdb(c.from);
  const b = tdb(c.to);
  const spec = { body: c.body, targetDeg: c.targetDeg, fromTdbSec: a, toTdbSec: b };

  const t0 = Date.now();
  const aberrated = searchAberratedLongitude(eph, spec);
  const abMs = Date.now() - t0;
  const t1 = Date.now();
  const retarded = searchRetardedLongitude(eph, spec);
  const ltMs = Date.now() - t1;
  let geometric = null;
  try {
    geometric = searchGeometricLongitude(eph, { body: c.body, targetDeg: c.targetDeg, fromTtDays: a / DAY, toTtDays: b / DAY });
  } catch (error) {
    geometric = { refused: error.code ?? String(error) };
  }

  const refAb = ref.crossings(c.body, c.targetDeg, a, b, STEP[c.body], true);
  const refLt = ref.crossings(c.body, c.targetDeg, a, b, STEP[c.body], false);
  const m = pair(aberrated.events, refAb.roots);
  const worst = m.matched.length ? Math.max(...m.matched.map((x) => Math.abs(x.delta))) : null;
  const allBracketed = m.matched.every((x) => x.got.bracketTdbSec[0] <= x.ref && x.ref <= x.got.bracketTdbSec[1]);

  // What each rung added, on the cases where all three found the same count.
  let ladder = null;
  if (geometric && !geometric.refused
    && geometric.events.length === retarded.events.length
    && retarded.events.length === aberrated.events.length
    && aberrated.events.length > 0) {
    ladder = aberrated.events.map((e, i) => ({
      crossing: i,
      lightTimeSec: retarded.events[i].tdbSec - geometric.events[i].ttDays * DAY,
      aberrationSec: e.tdbSec - retarded.events[i].tdbSec,
      referenceAberrationSec: refAb.roots[i] !== undefined && refLt.roots[i] !== undefined
        ? refAb.roots[i] - refLt.roots[i] : null,
    }));
  }

  rows.push({
    ...c,
    status: aberrated.execution.status,
    established: aberrated.completeness.established,
    isExactTotal: aberrated.eventCount.isExactTotal,
    found: aberrated.events.length,
    referenceRoots: refAb.roots.length,
    missed: m.missed.length,
    extra: m.extra.length,
    worstDeltaSec: worst,
    // `.every()` on an empty array is true, so on a zero-root case this
    // flag says nothing. `matchedRoots` is what makes it meaningful.
    everyReferenceRootBracketed: allBracketed,
    matchedRoots: m.matched.length,
    widestBracketSec: aberrated.events.length ? Math.max(...aberrated.events.map((e) => e.bracketWidthSec)) : null,
    unresolved: aberrated.accounting.unresolved.length,
    unresolvedWhy: aberrated.accounting.unresolved.slice(0, 2).map((u) => u.why),
    cells: aberrated.execution.cells,
    evaluations: aberrated.execution.evaluations,
    ms: abMs,
    worstObserverSpeedOverC: aberrated.diagnostics.aberration.worstObserverSpeedOverC,
    referenceStepSec: refAb.stepSec,
    referenceSamples: refAb.samples,
    lightTimeRung: {
      status: retarded.execution.status,
      established: retarded.completeness.established,
      found: retarded.events.length,
      referenceRoots: refLt.roots.length,
      evaluations: retarded.execution.evaluations,
      ms: ltMs,
    },
    geometricRung: geometric && geometric.refused
      ? { refused: geometric.refused }
      : { established: geometric.completeness.established, found: geometric.events.length },
    ladder,
  });
  process.stderr.write(`${c.id} ${c.body} ${c.targetDeg} -> ${aberrated.events.length}/${refAb.roots.length}`
    + ` est=${aberrated.completeness.established} ${abMs}ms\n`);
}

// ---- the preregistered pass rule, section 9, applied rather than eyeballed
const problems = [];
for (const r of rows) {
  const decided = r.established || (r.unresolved > 0 || r.status !== 'finished');
  if (!decided) problems.push(`${r.id}: neither established completeness nor gave a reason`);
  if (r.isExactTotal && r.unresolved > 0) problems.push(`${r.id}: an exact total with ${r.unresolved} unresolved intervals`);
  if (r.missed) problems.push(`${r.id}: missed ${r.missed} reference roots`);
  if (r.extra) problems.push(`${r.id}: reported ${r.extra} roots the reference does not have`);
  if (r.worstDeltaSec !== null && r.worstDeltaSec > ROOT_TOLERANCE_SEC) {
    problems.push(`${r.id}: worst root separation ${r.worstDeltaSec} s exceeds ${ROOT_TOLERANCE_SEC} s`);
  }
  if (!r.everyReferenceRootBracketed) problems.push(`${r.id}: a reference root lies outside its reported bracket`);
  // The ladder, in the pass rule rather than only in the record. It was
  // recorded and not checked, so `passed: true` rested on no ladder test
  // at all while the results document said the harness asserted one.
  for (const [i, l] of (r.ladder ?? []).entries()) {
    if (l.referenceAberrationSec === null) {
      problems.push(`${r.id}: crossing ${i} has no reference shift to compare the ladder against`);
    } else if (Math.abs(l.aberrationSec - l.referenceAberrationSec) > 2 * ROOT_TOLERANCE_SEC) {
      problems.push(`${r.id}: crossing ${i} shifted ${l.aberrationSec} s between rungs, the reference predicts ${l.referenceAberrationSec} s`);
    }
  }
  if (r.found > 0 && !r.ladder) problems.push(`${r.id}: found ${r.found} crossings but no rung comparison was made`);
}
const establishedCount = rows.filter((r) => r.established).length;
// Section 9's usefulness gate: fewer than half establishing completeness
// means the extension is recorded as not practical at this cost.
const usefulness = { established: establishedCount, of: rows.length, passes: establishedCount * 2 >= rows.length };
const withRoots = rows.filter((r) => r.found > 0).length;

const record = {
  ranAt: new Date().toISOString(),
  rule: 'ABERRATED-PREREGISTRATION.md section 8a',
  pack: {
    path: PACK,
    digest: rt.integrity.computedDigest,
    payloadSha256: rt.header.payloadSha256 ?? null,
    compiler: rt.header.compiler?.version ?? null,
    coverageTdbSec: [rt.coverage.startEtSecTdb, rt.coverage.stopEtSecTdb],
  },
  tolerances: { rootToleranceSec: ROOT_TOLERANCE_SEC, matchWindowSec: MATCH_WINDOW_SEC, referenceStepSec: STEP },
  rows,
  summary: {
    cases: rows.length,
    established: establishedCount,
    casesWithRoots: withRoots,
    totalRootsFound: rows.reduce((n, r) => n + r.found, 0),
    totalReferenceRoots: rows.reduce((n, r) => n + r.referenceRoots, 0),
    missed: rows.reduce((n, r) => n + r.missed, 0),
    extra: rows.reduce((n, r) => n + r.extra, 0),
    worstDeltaSec: Math.max(...rows.map((r) => r.worstDeltaSec ?? 0)),
    worstBracketSec: Math.max(...rows.map((r) => r.widestBracketSec ?? 0)),
    unresolvedIntervals: rows.reduce((n, r) => n + r.unresolved, 0),
    totalEvaluations: rows.reduce((n, r) => n + r.evaluations, 0),
    totalCells: rows.reduce((n, r) => n + r.cells, 0),
    totalMs: rows.reduce((n, r) => n + r.ms, 0),
    worstObserverSpeedOverC: Math.max(...rows.map((r) => r.worstObserverSpeedOverC)),
    aberrationShiftRangeSec: (() => {
      const all = rows.flatMap((r) => (r.ladder ?? []).map((l) => l.aberrationSec));
      return all.length ? [Math.min(...all), Math.max(...all)] : null;
    })(),
    worstLadderResidualSec: (() => {
      const all = rows.flatMap((r) => (r.ladder ?? [])
        .filter((l) => l.referenceAberrationSec !== null)
        .map((l) => Math.abs(l.aberrationSec - l.referenceAberrationSec)));
      return all.length ? Math.max(...all) : null;
    })(),
  },
  usefulness,
  passed: problems.length === 0 && usefulness.passes,
  problems,
};
rt.dispose();

const text = `${JSON.stringify(record, null, 2)}\n`;
if (OUT) writeFileSync(OUT, text);
process.stdout.write(`${JSON.stringify({ summary: record.summary, usefulness, passed: record.passed, problems }, null, 2)}\n`);
if (!record.passed) process.exitCode = 1;
