/**
 * Loads one zone's offset history before 1970 from the pinned tzdb release
 * with its backzone records (src/data/tz-history/, generated by
 * scripts/build-tz-history.mjs). Imported lazily by prepareLocalTime, so
 * neither this map nor the data is in any page's initial script.
 */
export interface ZoneHistory {
  /** Transitions before 1970, Unix seconds, ascending. */
  readonly t: readonly number[];
  /** Offsets in seconds east: before t[0], then after each transition. */
  readonly o: readonly number[];
}

const BUCKETS = import.meta.glob<{ zones: Record<string, ZoneHistory> }>(
  '../../data/tz-history/2025c/[0-9][0-9].json',
  { import: 'default' },
);

/** The file a name's history is in; scripts/build-tz-history.mjs hashes names the same way. */
export function historyBucket(name: string): string {
  let hash = 0x811c9dc5;
  for (let index = 0; index < name.length; index += 1) {
    hash ^= name.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return String(hash % 64).padStart(2, '0');
}

/** The pinned history of a zone name, or null when the release has none the browser's data should give way to. */
export async function loadZoneHistory(name: string): Promise<ZoneHistory | null> {
  const load = BUCKETS[`../../data/tz-history/2025c/${historyBucket(name)}.json`];
  if (!load) return null;
  const { zones } = await load();
  return Object.prototype.hasOwnProperty.call(zones, name) ? zones[name] : null;
}
